config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pools do
  # adding show
    resources :bookings, only: [:new, :show, :create,:update, :edit, :index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :bookings, only: [:destroy]

  resources :user, only: [] do
    collection do
      get :profile
      get :bookings
      get :pools
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pool
  validates :end_date, presence: true
  validates :start_date, presence: true, date: { after_or_equal_to: Proc.new { Date.today }, message: "must be at least #{(Date.today ).to_s}" }
  validate :end_date_is_after_start_date

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date")
    end
    if end_date == start_date
      errors.add(:end_date, "cannot be the same as start date")
    end
  end

   # validate :overlapping

  private

  # def overlapping
  #   if Booking.where('? <  end_date and ? > start_date', self.start_date, self.end_date).any?
  #     errors.add(:end_date, 'it overlaps another')
  #   end
  # end
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_hour, presence: true
  has_one_attached :photo
  geocoded_by :address
  validates :photo, presence: true

  after_validation :geocode
  after_validation :geocode, if: :will_save_change_to_address?


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :pools
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
    { host: ENV["www.rentapool.today"] || "localhost:3000" }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @pool = Pool.find(params[:pool_id])
    @booking = Booking.new
  end

  def create
    @pool = Pool.find(params[:pool_id])
    @booking = Booking.new(booking_params)
    @booking.pool = @pool
    @booking.user = current_user

    if
      @booking.save
      redirect_to pool_booking_path(@pool, @booking)
    else
      render :new
    end

  end

  def edit
    @pool = Pool.find(params[:pool_id])
  end

  def update
    @pool = Pool.find(params[:pool_id])
      if @booking.update(booking_params)
      redirect_to  pool_booking_path(@pool, @booking)
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_user_index_path
  end



  private

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date")
    end
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show ]
  before_action :find_pool, only: [:show, :edit,:update, :destroy]

  def index
    @pools = Pool.all

    @markers = @pools.geocoded.map do |pool|
      {
        lat: pool.latitude,
        lng: pool.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { pool: pool })
      }
    end

    if params[:address].present?
      @pools = Pool.where("address ILIKE ?", "%#{params[:address]}%")
    else
     @pools = Pool.all
    end
  end

  def new
    @pool = Pool.new
  end

  def create
    @pool = Pool.new(pool_params)
    @pool.user = current_user
      if @pool.save
        redirect_to pool_path(@pool)
      else
        render 'new'
    end
  end

  def show
    @user = @pool.user
    @pools = Pool.all
  end

  def edit
  end

  def update
    @pool.update(pool_params)
    redirect_to pool_path(@pool)
  end

  def destroy
    @pool.destroy
    redirect_to pools_user_index_path
  end

  private


  def find_pool
    @pool = Pool.find(params[:id])
  end

  def pool_params
    params.require(:pool).permit(:name, :description, :price_hour, :photo, :address)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def profile;end
  def bookings;end
  def pools;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookings/edit.html.erb
<div class="container col-4 mt-5">
  <h1>Your booking</h1>
  <%= simple_form_for [@pool, @booking] do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <%end %>
  <%= link_to "back",  profile_user_index_path %>
</div>

app/views/bookings/index.html.erb
<div class="container col-12 ml-2 d-flex wrapper-pools" style="background-color:#F3FBFC">
  <div class="cta-traits">
    <%= link_to "See more pools", pools_path %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container col-xl-4 col-md-8 col-sm-12 mt-5">
  <div class="reservation-card">
    <div class="reservation-title">
      <h1>Book your Pool</h1>
    </div>
    <%= simple_form_for [@pool, @booking] do |f| %>
    <div class="booking-inputs">
      <div class="booking-start-date">
        <%= f.input :start_date, as: :date, html5: true %>
      </div>
      <div class="booking-end-date">
      <%= f.input :end_date, as: :date, html5: true %>
      </div>
    </div>
    <div class="booking-button">
      <%= f.button :submit, class: 'new-reservation-btn', value: "Confirm Booking" %>
    </div>
    <%end %>
    <div class="booking-cancel">
      <%= link_to "Cancel", pools_path, class: 'cancel-new-reservation' %>
    </div>

  </div>

</div>

app/views/bookings/show.html.erb
<div class="booking-confirmation-container">
  <div class="confirmation-container">
    <div class="new-booking-done">
        <h1>Yay! 🎉</h1> <h2>Your reservation is confirmed.</h2>
        <h5><!-- Total   ???
        reservation.end_date - reservation_start.date = days / days * reservation.price?</h5> -->
        <div class="cta-traits">
          <%= link_to "See more pools", pools_path %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= stylesheet_pack_tag 'application'%>
    <!-- added font-awesome, bootstrap, google fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('cover.png') %>



    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body style="margin-top:-40px">
    <nav class="navbar navbar-expand-lg" style="font-family: 'Roboto', sans-serif;">
      <div class="navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <!-- shows quurks in navbar when not on the home page -->
          <% if !current_page?(root_path) %>
            <%= link_to "SPLASH", root_path, class: "nav-link home splash" %>
            <% end %>
          <!-- for the rest of the navbar -->
          <!-- if user is logged in -->
          <% if current_user %>
            <!-- Logged in as <%= current_user.email %> -->
              <li class="nav-item dropdown mt-1">
                <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "User Profile", profile_user_index_path, class: "dropdown-item" %>
                  <%= link_to "Your Reservations", bookings_user_index_path, class: "dropdown-item" %>
                  <%= link_to "Your Pools", pools_user_index_path, class: "dropdown-item" %>
                </div>
              </li>
              <li class="nav-item logout">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item add-pool">
              <%= link_to "Add Pool", new_pool_path, class: "btn btn-outline-secondary mt-1 "  %>
            </li>
            <li class="nav-item"> <%= link_to "SPLASH", root_path, class: "nav-link home splash" %><li>
          <% else %>
          <!-- if user isn't logged in -->
          <%= link_to "SPLASH", root_path, class: "nav-link home splash" %>
            <li class="nav-item dropdown mt-1">
              <%= link_to (image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false), profile_user_index_path  %>
            </li>
            <li class="nav-item logout">
              <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item sign-up">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link sign-up"  %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/_landing_form.html.erb
<%= form_tag pools_path, method: :get do %>
  <div class="mt-5 product-search">

    <div class="search-element">
      <%= text_field_tag :address,
        params[:address],
        class: "search-input",
        placeholder: "Search by City"
      %>
    </div>
    <%= submit_tag "Search", class: "search-button" %>
  </div>
<% end %>

app/views/pages/home.html.erb
<body class="home">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dhjbcdzxb/image/upload/v1611606710/unsplashpool2_z7foy8.jpg);">
    <div class="container text-center" style="margin-top:-120px">
      <p class="text mb-5">Swimming Pools to Rent Worldwide<p>
      <%= render 'landing_form' %>
      <div class="cta"><%= link_to "Dive in", pools_path%></div>
    </div>
  </div>
</body>

app/views/pools/_form.html.erb
<div class="container" style="background-color:#F3FBFC">
  <%= simple_form_for @pool do |f|%>
    <%= f.input :name %>
    <!-- go to schema and change description to a text input instead of string -->
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :price_hour %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/pools/_info_window.html.erb
<% if pool.photo.attached? %>
  <h2 class="text-center"><%= pool.name %></h2>
  <%= link_to pool_path(pool)  do %>
  <div><%= cl_image_tag pool.photo.key, height: 200, width: 200, class: "mt-2" %></div>
  <% end %>
<% end %>

app/views/pools/edit.html.erb
<div class="container col-6 mt-5">
  <h1>Create a new Pool</h1>
  <%= render "form", pool: @pool %>
  <div class="btn">
    <%= link_to "Cancel", pools_path %>
  </div>
</div>

app/views/pools/index.html.erb
<div class="container col-12 ml-2 d-flex" style="background-color:#F3FBFC">
   <div class="back-button-index">
    <%= link_to :back do %>
      <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        viewBox="0 0 492 492" width="20px" fill="#151515" style="enable-background:new 0 0 492 492;" xml:space="preserve">
        <path d="M198.608,246.104L382.664,62.04c5.068-5.056,7.856-11.816,7.856-19.024c0-7.212-2.788-13.968-7.856-19.032l-16.128-16.12
          C361.476,2.792,354.712,0,347.504,0s-13.964,2.792-19.028,7.864L109.328,227.008c-5.084,5.08-7.868,11.868-7.848,19.084
          c-0.02,7.248,2.76,14.028,7.848,19.112l218.944,218.932c5.064,5.072,11.82,7.864,19.032,7.864c7.208,0,13.964-2.792,19.032-7.864
          l16.124-16.12c10.492-10.492,10.492-27.572,0-38.06L198.608,246.104z"/>
      </svg>
    <% end %>
  </div>
  <div class= "wrapper-pools">
    <div class="col-6 card-pool">
      <% if @pools.count >= 1 %>
        <% @pools.each do |pool| %>
          <% if pool.photo.attached? %>
            <div class="card-product mb-3 pool-product">
              <%= link_to pool_path(pool) do %>
                <img src="<%= cl_image_path pool.photo.key %>"/>
                <div class="card-product-infos">
                <%end%>
                <h2><%=link_to pool.name, pool_path(pool) %></h2>
                <p><%= truncate(pool.description, length: 47, separator: ' ') %></p>
                <p class="mt-2"><%= truncate(pool.address) %></p>
                <p><span class="price"><%= pool.price_hour %>€ p/day</span></p>
                </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>Sorry 🥺 no pools were found</p>
      <% end %>
    </div>
    <div id="map"
       style="width: 100%; height: 90vh         ";
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/pools/new.html.erb
<div class="container col-lg-7 col-md-10 col-sm-10 mt-5">
  <h1>Create a new Pool</h1>
  <%= render "form", pool: @pool %>
  <div class="btn">
    <%= link_to "Cancel", pools_path %>
  </div>
</div>

app/views/pools/show.html.erb
<div class="container">
  <div class="back-button-index">
    <%= link_to :back do %>
      <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        viewBox="0 0 492 492" width="20px" fill="#151515" style="enable-background:new 0 0 492 492;" xml:space="preserve">
        <path d="M198.608,246.104L382.664,62.04c5.068-5.056,7.856-11.816,7.856-19.024c0-7.212-2.788-13.968-7.856-19.032l-16.128-16.12
          C361.476,2.792,354.712,0,347.504,0s-13.964,2.792-19.028,7.864L109.328,227.008c-5.084,5.08-7.868,11.868-7.848,19.084
          c-0.02,7.248,2.76,14.028,7.848,19.112l218.944,218.932c5.064,5.072,11.82,7.864,19.032,7.864c7.208,0,13.964-2.792,19.032-7.864
          l16.124-16.12c10.492-10.492,10.492-27.572,0-38.06L198.608,246.104z"/>
      </svg>
    <% end %>
  </div>
  <h1><%= @pool.name %> <span class="ml-1">by <%= @user.first_name %></span></h1>
  <div class="flex-container-trait mb-5 wrapper-show">
    <div class="container-trait-description mt-5">
      <div class="pool-description">
        <p><%= truncate(@pool.description, length: 100, separator: ' ')%></p>
        <p><%= @pool.price_hour %>€ p/day</p>
        <p><%= @pool.address %></p>
      </div>
      <div class="book-trait-button">
        <button type="button" class="btn book-trait btn-lg">
          <%= link_to "Book this pool", new_pool_booking_path(@pool) %>
        </button>
      </div>
    <!-- link to edit , delete, back to traits list -->
    </div>
    <% if @pool.photo.attached? %>
      <div class="traits-image mt-5">
        <%= cl_image_tag @pool.photo.key, height: 300, width: 400, crop: :fill %>
      </div>
    <% end %>
  </div>
</div>
  <div class="container col-12  justify-content-center" style="background-color:#F3FBFC">
    <div class="container-fluid col-8 text-center other-pools-wrapper">
      <h2 class="other-pools-title">Check other pools</h2>
      <div class="row mx-auto mt-5 ml-5 justify-content-center">
        <% @pools.sample(3).each do |pool| %>
          <% if pool.photo.attached? %>
            <div class="card ml-4 mb-3" style="width: 15rem">
               <%= link_to pool_path(pool) do %>
                <img class="card-img-top" style="height:200px"src="<%= cl_image_path pool.photo.key%>">
                <div class="card-body">
                  <h5><%= pool.name%></h5>
                  <p class="card-text"><%= pool.address %><span class="ml-5 mt-3"><%= pool.price_hour %> p/day €</span></p>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/user/bookings.html.erb
<div class="trait_user_container" style="background-color:#F3FBFC; height:300vh">
  <div class="back-button-index mt-3 ml-3">
    <%= link_to :back do %>
      <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        viewBox="0 0 492 492" width="20px" fill="#151515" style="enable-background:new 0 0 492 492;" xml:space="preserve">
        <path d="M198.608,246.104L382.664,62.04c5.068-5.056,7.856-11.816,7.856-19.024c0-7.212-2.788-13.968-7.856-19.032l-16.128-16.12
          C361.476,2.792,354.712,0,347.504,0s-13.964,2.792-19.028,7.864L109.328,227.008c-5.084,5.08-7.868,11.868-7.848,19.084
          c-0.02,7.248,2.76,14.028,7.848,19.112l218.944,218.932c5.064,5.072,11.82,7.864,19.032,7.864c7.208,0,13.964-2.792,19.032-7.864
          l16.124-16.12c10.492-10.492,10.492-27.572,0-38.06L198.608,246.104z"/>
      </svg>
    <% end %>
  </div>
  <h1 class="title-user mt-5"><%=current_user.first_name.capitalize%>, your reservations</h1>
  <div class="container mx-auto">
    <% current_user.bookings.each do |booking| %>
      <% if booking.pool.photo.attached?  %>
        <div class="card-product mb-3 mx-auto">
          <%= link_to pool_path(booking.pool) do %>
          <img src="<%= cl_image_path booking.pool.photo.key %>"/>
          <div class="card-product-infos">
          <%end%>
            <h2><%= booking.pool.name.capitalize %></h2>
            <div class="booking-date">
              <p>
                <strong>From:</strong><%= booking.start_date%>
                <strong>To:</strong><%= booking.end_date %>
              </p>
            </div>
            <div class="pool-btns" >
              <div class="d-flex ml-2">
                <div class="edit_green_btn ml-5">
                  <%= link_to "Edit",  edit_pool_booking_path(booking.pool, booking) %>
                </div>
                <div class="delete_coral_btn ml-5">
                 <%= link_to "Delete", booking_path(booking), method: :delete, data: {confirm: "are you sure?"}%>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/user/pools.html.erb
<div class="trait_user_container" style="background-color:#F3FBFC; height:300vh">
  <div class="back-button-index mt-3 ml-3">
    <%= link_to :back do %>
      <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        viewBox="0 0 492 492" width="20px" fill="#151515" style="enable-background:new 0 0 492 492;" xml:space="preserve">
        <path d="M198.608,246.104L382.664,62.04c5.068-5.056,7.856-11.816,7.856-19.024c0-7.212-2.788-13.968-7.856-19.032l-16.128-16.12
          C361.476,2.792,354.712,0,347.504,0s-13.964,2.792-19.028,7.864L109.328,227.008c-5.084,5.08-7.868,11.868-7.848,19.084
          c-0.02,7.248,2.76,14.028,7.848,19.112l218.944,218.932c5.064,5.072,11.82,7.864,19.032,7.864c7.208,0,13.964-2.792,19.032-7.864
          l16.124-16.12c10.492-10.492,10.492-27.572,0-38.06L198.608,246.104z"/>
      </svg>
    <% end %>
  </div>
  <h1 class="title-user mt-5"><%=current_user.first_name.capitalize%>, your listed pools</h1>
  <div class="container mx-auto">
    <% current_user.pools.each do |pool| %>
      <% if pool.photo.attached?  %>
        <div class="card-product mb-3 mx-auto">
          <%= link_to pool_path(pool) do %>
          <img src="<%=cl_image_path pool.photo.key%>"/>
          <div class="card-product-infos">
          <%end%>
            <h2><%=link_to pool.name, pool_path(pool) %></h2>
            <div class="description">
              <p class="mt-2"><%= truncate(pool.description, length: 47, separator: ' ') %></p>
              <p class="mt-1"><%= pool.address %></p>
            </div>
            <div class="pool-price">
              <p class="mt-5"><span class="price"><%= pool.price_hour %>€ p/hour</span></p>
            </div>
            <div class="pool-btns">
              <div class="d-flex ml-3">
                <div class="edit_green_btn ml-5">
                  <%= link_to "Edit",  edit_pool_path(pool) %>
                </div>
                <div class="delete_coral_btn ml-5">
                  <%= link_to "Delete", pool_path(pool), method: :delete, data: {confirm: "are you sure?"}%>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/user/profile.html.erb
<div class="user_container col-lg-8 col-sm-6" style="background-color:#F3FBFC">
<div class="back-button-index mt-3 ml-3">
  <%= link_to :back do %>
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      viewBox="0 0 492 492" width="20px" fill="#151515" style="enable-background:new 0 0 492 492;" xml:space="preserve">
      <path d="M198.608,246.104L382.664,62.04c5.068-5.056,7.856-11.816,7.856-19.024c0-7.212-2.788-13.968-7.856-19.032l-16.128-16.12
        C361.476,2.792,354.712,0,347.504,0s-13.964,2.792-19.028,7.864L109.328,227.008c-5.084,5.08-7.868,11.868-7.848,19.084
        c-0.02,7.248,2.76,14.028,7.848,19.112l218.944,218.932c5.064,5.072,11.82,7.864,19.032,7.864c7.208,0,13.964-2.792,19.032-7.864
        l16.124-16.12c10.492-10.492,10.492-27.572,0-38.06L198.608,246.104z"/>
    </svg>
  <% end %>
</div>
<h1 class="title-user mt-5">Hello <%=current_user.first_name.capitalize%></h1>
<div class="container mx-auto">
  <div class="user_info">
    <p class="mb-2">First Name</p><div class="mb-3 info"><%= current_user.first_name.capitalize %></div>
    <p>Last Name</p><div class=" mb-3 info"><%= current_user.last_name.capitalize %></div>
    <p>Email</p><div class="info mb-3"><%= current_user.email %></div>
    <div class="text-center mb-5">
      <div class="btn btn-outline-info">
          <%= link_to "Edit Profile",  edit_user_registration_path %>
      </div>
    </div>
  </div>
</div>
</div>